tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]])

In [21]:
import torch
a=torch.arange(0,3*3*4)
a=a.reshape(3,3,4)

print(a)
for i in range(3):
    output=torch.ones(a.shape[0]).reshape(-1,1)
    output*=(i+1)
    
    a = a[1:, :, :]
    
    a[:,-1,0]=output[:-1].reshape(-1)
    print(a)
    
    
    

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]])
tensor([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [ 1, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [ 1, 33, 34, 35]]])
tensor([[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [ 2, 33, 34, 35]]])
tensor([], size=(0, 3, 4), dtype=torch.int64)
